version: '3.8'

services:
  postgres:
    container_name: users_db
    image: postgres:latest
    ports:
      - '5430:5432'
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres