version: '3.8'

services:
  postgres:
    container_name: notifications_db
    image: postgres:latest
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_DB=notifications_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres