server:
  port: 8009

spring:
  cloud:
     gateway:
      routes:
        - id: users_route
          uri: http://localhost:8191/
          predicates:
             - Path=/api/users/**
        - id: friends_route
          uri: http://localhost:8192/
          predicates:
            - Path=/api/friends/**