app:
  id: ${MESSENGER_APP_ID:shibanov.leonid}
  security:
    jwt-token:
      permit-all:
        - /api/users/register
        - /api/users/login
      root-path: /api
      secret: qqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrttty
      issuer: messenger-api
      subject: User details
    integrations:
      root-path: /integration
      api-key: ac816388c1c44ac2b2ae431f89c82e7e345d25a0e6474e75a78f9a5ce496060c

spring:
  application:
    name: users
  flyway:
    locations: classpath:migrations
    url: jdbc:postgresql://localhost:5432/users_db
    user: hits
    password: hits
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: hits
    password: hits
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:rmq-user}
    password: ${RABBITMQ_PASSWORD:rmq-pass}
  cloud.stream.bindings:
    userSuccessfulLoginEvent-out-0:
      destination: ${app.id}_USER_EVENT_SUCCESSFUL_LOGIN

integration:
  request:
    check-existence-in-blacklist: http://localhost:8192/integration/blacklist/check-existence-in-blacklist

server:
  port: 8191