version: '3.8'

services:
  postgres:
    container_name: file_storage_db
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=file_storage_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  minio:
    image: bitnami/minio:2023.4.28
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminqwerty
    volumes:
      - minio-data:/data
    ports:
      - 9900:9000
      - 9901:9001

volumes:
  minio-data:
