app:
  security:
    jwt-token:
      permit-all:
        - /api/users/register
        - /api/users/login
      root-path: /api
      secret: qqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrttty
      issuer: messenger-api
      subject: User details
    integrations:
      root-path: /integration
      api-key: ac816388c1c44ac2b2ae431f89c82e7e345d25a0e6474e75a78f9a5ce496060c

spring:
  application:
    name: chat
  flyway:
    locations: classpath:migrations
    url: jdbc:postgresql://localhost:5432/chats_db
    user: hits
    password: hits
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/chats_db
    username: hits
    password: hits
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

integration:
  request:
    check-existence-by-id: http://localhost:8191/integration/users/check-existence-by-id

server:
  port: 8193