app:
  id: ${MESSENGER_APP_ID:shibanov.leonid}
  security:
    jwt-token:
      permit-all:
        - /api/users/register
        - /api/users/login
        - /api/files/**
      root-path: /api
      secret: qqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrttty
      issuer: messenger-api
      subject: User details
    integrations:
      root-path: /integration
      api-key: ac816388c1c44ac2b2ae431f89c82e7e345d25a0e6474e75a78f9a5ce496060c

spring:
  application:
    name: chat
  flyway:
    locations: classpath:migrations
    url: jdbc:postgresql://localhost:5432/chats_db
    user: hits
    password: hits
  datasource:
    url: jdbc:postgresql://localhost:5432/chats_db
    username: hits
    password: hits
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:rmq-user}
    password: ${RABBITMQ_PASSWORD:rmq-pass}
  cloud.stream.bindings:
    newNotificationEvent-out-0:
      destination: ${app.id}_NEW_NOTIFICATION_EVENT
    userDataSynchronizationEvent-in-0:
      destination: ${app.id}_USER_DATA_SYNCHRONIZATION_EVENT

integration:
  request:
    check-existence-by-id: http://localhost:8191/integration/users/check-existence-by-id
    check-existence-in-friends: http://localhost:8192/integration/friends/check-existence-in-friends
    check-multi-existence-in-friends: http://localhost:8192/integration/friends/check-multi-existence-in-friends
    get-full-name-and-avatar: http://localhost:8191/integration/users/get-full-name-and-avatar
    check-multi-attachment-existence: http://localhost:8195/integration/files/check-multi-attachment-existence
    check-avatar-id-existence: http://localhost:8195/integration/files/check-avatar-id-existence/{id}
    get-filename: http://localhost:8195/integration/files/get-filename/{id}
    get-file-size: http://localhost:8195/integration/files/get-file-size/{id}


server:
  port: 8193